# Generated by Django 3.1.5 on 2021-01-05 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='description',
            field=models.CharField(default='first test class', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='name',
            field=models.CharField(default='test', max_length=32),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking_app.classroom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
